apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        run: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        - name: PORT
            value: "{{ .Values.service.externalPort }}:{{.Values.service.internalPort}}"
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.path}}
              port: {{.Values.livenessProbe.port}}
          readinessProbe:
            httpGet:
              path: {{.Values.readinessProbe.path}}
              port: {{.Values.readinessProbe.port}}
          resources:
                   {{}}
