apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 
      externalPort: {{.Values.service.externalPort}}
      internalPort: {{.Values.service.internalPort}}
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
      targetPort: {{ .Values.service.externalPort }}
  selector:
      run: {{ .Chart.Name }}